#ifndef RETURN_STATUS_H
#define RETURN_STATUS_H

typedef enum {
    RETURN_STATUS_OK = 0,
    RETURN_STATUS_ERROR = 1,
    RETURN_STATUS_NOT_INITIALIZED = 2,
    RETURN_STATUS_TIMEOUT = 3,
    RETURN_STATUS_NOT_FOUND = 4,
    RETURN_STATUS_INVALID_PARAM = 5,
    RETURN_STATUS_NOT_PERMITTED = 6,
} RETURN_STATUS_t;

const char* RETURN_STATUS_Module(RETURN_STATUS_t status);

#endif // RETURN_STATUS_H